# Generated by Django 4.1.7 on 2023-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('metodopago', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('fecha_ingreso', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=10)),
                ('productos', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
