# Generated by Django 4.1.7 on 2023-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipotarjeta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=10)),
                ('productos', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
    ]
