# Generated by Django 4.1.7 on 2023-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipotarjeta',
            new_name='metodopago',
        ),
    ]
