# Generated by Django 4.1.7 on 2023-05-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.productos')),
            ],
            options={
                'verbose_name': 'Detalle Producto',
                'verbose_name_plural': 'Detalle de productos',
            },
        ),
    ]
